### ISSUE TITLE
[linux] Hat left is ignored completely

### ISSUE THREAD

**Issue by Loader009** [AlexanderDzhoganov/ksp-advanced-flybywire#32] opened 2015-01-17 10:59 UTC
JoyStick: Microsoft SideWinder Force Feedback 2

Hat buttons which are detected:
- center (no button, see #31 )
- up
- up+right
- right
- down+right
- down

Hat buttons which are not detected:
- up+left
- left
- left+down

No hardware-issue.
My second JoyStick (the same type) has this issue also.

**Comment by AlexanderDzhoganov** [comment] 2015-02-25 10:37
Thanks for the report, could you test with AFBW 1.5 and report back?

**Comment by AlexanderDzhoganov** [comment] 2015-12-16 22:05
This has been up a while so I'm closing it. Please reopen if the issue is still present.

**Closed by AlexanderDzhoganov** 2015-12-16 22:05 UTC
